# Generated by Django 4.1 on 2022-08-24 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nucleus', '0004_user_phone_number_vendor'),
        ('main_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nucleus.vendor'),
        ),
    ]
