# Generated by Django 4.1 on 2022-08-25 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nucleus', '0008_address_address_user_is_vendor_alter_user_age_and_more'),
        ('main_store', '0005_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='key_features',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='specifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='vendor',
            field=models.ForeignKey(blank=True, default='Official Store', null=True, on_delete=django.db.models.deletion.SET_NULL, to='nucleus.vendor'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField()),
                ('rating', models.CharField(choices=[('1', '*'), ('2', '**'), ('3', '***'), ('4', '****'), ('5', '******')], max_length=1, null=True)),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_store.item')),
            ],
        ),
    ]
