# Generated by Django 4.1 on 2022-08-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_store', '0006_item_key_features_item_specifications_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='discount_price',
        ),
        migrations.AddField(
            model_name='item',
            name='discount',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Amount to be removed from ORIGINAL PRICE', null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.CharField(blank=True, choices=[('1', '*'), ('2', '**'), ('3', '***'), ('4', '****'), ('5', '******')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='ordereditem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
