# Generated by Django 4.1 on 2022-08-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_store', '0007_remove_item_discount_price_item_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='checkout_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
