# Generated by Django 4.1 on 2022-08-25 23:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_store', '0008_alter_cart_checkout_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='items',
            new_name='saved_items',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='checkout_date',
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=5000)),
                ('delivery', models.CharField(choices=[('D', 'Door Delivery'), ('P', 'Pick Up Station')], max_length=1, null=True)),
                ('payment_method', models.CharField(choices=[('Pay On Delivery', 'Pay On Delivery'), ('Pay With Card', 'Pay With Card'), ('Credit Card', 'Credit Card')], max_length=20, null=True)),
                ('checkout_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
