# Generated by Django 4.0.6 on 2022-07-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_tags_article_image_article_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['date_uploaded']},
        ),
        migrations.AlterField(
            model_name='article',
            name='date_updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='date_uploaded',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tags',
            name='name_of_tag',
            field=models.CharField(default='news', help_text='Enter a suitable tag to help find the post', max_length=15),
        ),
    ]
