# Generated by Django 4.0.6 on 2022-08-03 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
