# Generated by Django 4.0.6 on 2022-08-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_article_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
